#!/bin/bash

source /usr/share/yunohost/helpers

ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --app=$app --key=install_dir)
port=$(ynh_app_setting_get -a $app -k port)

#=================================================
# APPLYING CONFIG
#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply

    ynh_add_config --template="config.conf.template" --destination="$install_dir/simplytranslate/config.conf"

    chmod 400 "$install_dir/simplytranslate/config.conf"
    chown $app:$app "$install_dir/simplytranslate/config.conf"
}

#=================================================
# GENERIC FINALIZATION
#=================================================

ynh_app_config_run $1

