#!/bin/bash

source /usr/share/yunohost/helpers

#REMOVEME? ynh_abort_if_errors

#=================================================
# RETRIEVE ARGUMENTS
#=================================================

install_dir=$(ynh_app_setting_get --key=install_dir)
port=$(ynh_app_setting_get -a $app -k port)

#=================================================
# APPLYING CONFIG
#=================================================

ynh_app_config_apply() {
    _ynh_app_config_apply

    ynh_config_add --template="config.conf.template" --destination="$install_dir/simplytranslate/config.conf"

    #REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/simplytranslate/config.conf"
    #REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/simplytranslate/config.conf"
}

#=================================================

ynh_app_config_run $1
