#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# APP "BUILD" (DEPLOYING SOURCES, VENV, COMPILING ETC)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================
ynh_script_progression "Setting up source files..."

ynh_setup_source --dest_dir="$install_dir/simplytranslate"

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# SYSTEM CONFIGURATION
#=================================================
ynh_script_progression "Adding system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Web interface for SimplyTranslate" --log="/var/log/$app/$app.log"

#=================================================
# APP INITIAL CONFIGURATION
#=================================================
# ADD A CONFIGURATION
#=================================================
ynh_script_progression "Adding $app's configuration..."

# some default config
ynh_app_setting_set -a $app -k libretranslate_enable -v false
ynh_app_setting_set -a $app -k libretranslate_instance -v ""
ynh_app_setting_set -a $app -k libretranslate_api -v ""
ynh_app_setting_set -a $app -k google_enable -v true
ynh_app_setting_set -a $app -k deepl_enable -v false
ynh_app_setting_set -a $app -k reverso_enable -v false
ynh_app_setting_set -a $app -k iciba_enable -v false

# load the above config
libretranslate_enable=$(ynh_app_setting_get -a $app -k libretranslate_enable)
libretranslate_instance=$(ynh_app_setting_get -a $app -k libretranslate_instance)
libretranslate_api=$(ynh_app_setting_get -a $app -k libretranslate_api)
google_enable=$(ynh_app_setting_get -a $app -k google_enable)
deepl_enable=$(ynh_app_setting_get -a $app -k deepl_enable)
iciba_enable=$(ynh_app_setting_get -a $app -k iciba_enable)
reverso_enable=$(ynh_app_setting_get -a $app -k reverso_enable)

ynh_config_add --template="config.conf.template" --destination="$install_dir/simplytranslate/config.conf"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/simplytranslate/config.conf"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/simplytranslate/config.conf"

#=================================================
# CONFIGURATION FOR SUBPATH
#=================================================

if [ "$path" = "/" ]; then
	st_path=""
else
	st_path=$path
fi

ynh_replace -m "\"/?engine" -r "\"$st_path/?engine" -f "$install_dir/simplytranslate/templates/index.html"
ynh_replace -m "/prefs" -r "$st_path/prefs" -f "$install_dir/simplytranslate/templates/index.html"
ynh_replace -m "/switchlanguages" -r "$st_path/switchlanguages" -f "$install_dir/simplytranslate/templates/index.html"
ynh_replace -m "\"/\"" -r "\"$st_path/\"" -f "$install_dir/simplytranslate/templates/prefs.html"
ynh_replace -m "/prefs" -r "$st_path/prefs" -f "$install_dir/simplytranslate/templates/prefs.html"
ynh_replace -m "/api" -r "$st_path/api" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "/prefs" -r "$st_path/prefs" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "/switchlanguages" -r "$st_path/switchlanguages" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "f\"/?" -r "f\"$st_path/?" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "\"/\"" -r "\"$st_path/\"" -f "$install_dir/simplytranslate/main.py"

#=================================================
# BUILD THE APP
#=================================================
ynh_script_progression "Building the app..."

mkdir "$install_dir/venv"
python3 -m venv "$install_dir/venv"
"$install_dir/venv/bin/python3" -m pip install -r "$install_dir/simplytranslate/requirements.txt"

chown -R $app:$app "$install_dir/venv"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================
ynh_script_progression "Installation of $app completed"
