#!/bin/bash

source _common.sh
source /usr/share/yunohost/helpers

#=================================================
# IMPORT SOME CONFIG
#=================================================

libretranslate_enable=$(ynh_app_setting_get -a $app -k libretranslate_enable)
libretranslate_instance=$(ynh_app_setting_get -a $app -k libretranslate_instance)
libretranslate_api=$(ynh_app_setting_get -a $app -k libretranslate_api)
google_enable=$(ynh_app_setting_get -a $app -k google_enable)
deepl_enable=$(ynh_app_setting_get -a $app -k deepl_enable)
iciba_enable=$(ynh_app_setting_get -a $app -k iciba_enable)
reverso_enable=$(ynh_app_setting_get -a $app -k reverso_enable)
port=$(ynh_app_setting_get -a $app -k port)

#=================================================
# STOP SYSTEMD SERVICE
#=================================================
ynh_script_progression "Stopping $app's systemd service..."

ynh_systemctl --service=$app --action="stop"

#=================================================
# "REBUILD" THE APP (DEPLOY NEW SOURCES, RERUN NPM BUILD...)
#=================================================
# DOWNLOAD, CHECK AND UNPACK SOURCE
#=================================================

# FIXME: this is still supported but the recommendation is now to *always* re-setup the app sources wether or not the upstream sources changed
if ynh_app_upstream_version_changed
then
	ynh_script_progression "Upgrading source files..."

	ynh_setup_source --dest_dir="$install_dir/simplytranslate"
fi

#REMOVEME? Assuming the install dir is setup using ynh_setup_source, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown -R $app:www-data "$install_dir"
#=================================================
# CONFIGURATION FOR SUBPATH
#=================================================

if [ "$path" = "/" ]; then
	st_path=""
else
	st_path=$path
fi

ynh_replace -m "\"/?engine" -r "\"$st_path/?engine" -f "$install_dir/simplytranslate/templates/index.html"
ynh_replace -m "/prefs" -r "$st_path/prefs" -f "$install_dir/simplytranslate/templates/index.html"
ynh_replace -m "/switchlanguages" -r "$st_path/switchlanguages" -f "$install_dir/simplytranslate/templates/index.html"
ynh_replace -m "\"/\"" -r "\"$st_path/\"" -f "$install_dir/simplytranslate/templates/prefs.html"
ynh_replace -m "/prefs" -r "$st_path/prefs" -f "$install_dir/simplytranslate/templates/prefs.html"
ynh_replace -m "/api" -r "$st_path/api" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "/prefs" -r "$st_path/prefs" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "/switchlanguages" -r "$st_path/switchlanguages" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "f\"/?" -r "f\"$st_path/?" -f "$install_dir/simplytranslate/main.py"
ynh_replace -m "\"/\"" -r "\"$st_path/\"" -f "$install_dir/simplytranslate/main.py"

#=================================================
# REAPPLY SYSTEM CONFIGURATIONS
#=================================================
ynh_script_progression "Upgrading system configurations related to $app..."

ynh_config_add_nginx

ynh_config_add_systemd

yunohost service add $app --description="Web interface for SimplyTranslate" --log="/var/log/$app/$app.log"

#=================================================
# RECONFIGURE THE APP (UPDATE CONF, APPLY MIGRATIONS...)
#=================================================
# UPDATE A CONFIG FILE
#=================================================
ynh_script_progression "Updating configuration..."

ynh_config_add --template="config.conf.template" --destination="$install_dir/simplytranslate/config.conf"

#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chmod 400 "$install_dir/simplytranslate/config.conf"
#REMOVEME? Assuming the file is setup using ynh_config_add, the proper chmod/chowns are now already applied and it shouldn't be necessary to tweak perms | chown $app:$app "$install_dir/simplytranslate/config.conf"

#=================================================
# REBUILDING THE APP
#=================================================
ynh_script_progression "Rebuilding the app..."

ynh_safe_rm "$install_dir/venv"
mkdir "$install_dir/venv"
python3 -m venv "$install_dir/venv"
"$install_dir/venv/bin/python3" -m pip install -r "$install_dir/simplytranslate/requirements.txt"

chown -R $app:$app "$install_dir/venv"

#=================================================
# START SYSTEMD SERVICE
#=================================================
ynh_script_progression "Starting $app's systemd service..."

ynh_systemctl --service=$app --action="start"

#=================================================
# END OF SCRIPT
#=================================================

ynh_script_progression "Upgrade of $app completed"
